# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MiddleOut
email: sherin.thomas@cowrks.com, sricharanized@gmail.com, sudhanshu.passi@cowrks.com
description: > # this means to ignore newlines until "baseurl:"
  Efficient word vectors implementation which uses entirely different approach than state-of-the-art
  word2vec/GloVe vectors. Shamelessly stole the name from silicon valley series, we establish the middleout
  approach of upgrading the vecotor from both sides, backpropagating the error outwards from the middle.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://middleoutvectors.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllr
github_username:  middleoutvectors

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
